const SUPABASE_URL="PASTE_YOUR_SUPABASE_URL";const SUPABASE_ANON_KEY="PASTE_YOUR_SUPABASE_ANON_KEY";const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY),app=document.getElementById("app"),conn=document.getElementById("connection");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function boot(){if(SUPABASE_URL.startsWith("PASTE_"))return login("Configure admin.js first.");let{data:{session}}=await sb.auth.getSession();if(!session)return login();conn.textContent="Connected";dashboard()}
function login(msg=""){app.innerHTML=`<div class="login"><h2>Admin Login</h2>${msg?`<p class="muted">${esc(msg)}</p>`:""}<input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><button id="sign">Sign in</button></div>`;sign.onclick=async()=>{let{error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(error)alert(error.message);else boot()}}
async function count(t){let{count,error}=await sb.from(t).select("*",{count:"exact",head:true});if(error)throw error;return count||0}
async function dashboard(){let[v,l,c,g]=await Promise.all(["vocabulary","lessons","collections","grammar"].map(count));app.innerHTML=`<h2>Dashboard</h2><div class="grid"><div class="stat">Vocabulary<b>${v}</b></div><div class="stat">Lessons<b>${l}</b></div><div class="stat">Collections<b>${c}</b></div><div class="stat">Grammar<b>${g}</b></div></div><div class="panel" style="margin-top:14px"><h3>Architecture</h3><p>PostgreSQL master → protected API → mobile local DB → offline mode → incremental sync.</p></div>`}
async function tableView(t,title,cols){let{data,error}=await sb.from(t).select(cols.join(",")).limit(100);if(error)return app.innerHTML=`<div class="panel">${esc(error.message)}</div>`;app.innerHTML=`<h2>${title}</h2><div class="toolbar"><input id="q" placeholder="Search (display only)"><button id="ref">Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>${data.map(r=>`<tr>${cols.map(c=>`<td>${esc(typeof r[c]==="object"?JSON.stringify(r[c]):r[c])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;ref.onclick=()=>tableView(t,title,cols)}
function config(){app.innerHTML=`<h2>Front Config</h2><div class="panel"><p>Production editor will control theme, XP, hints, creativity bonus, feature flags and maintenance mode through <b>app_config</b>.</p></div>`}
function sync(){app.innerHTML=`<h2>Publish / Sync</h2><div class="panel"><p>Draft → Validate → Publish → increment database version → generate sync changes → clients download delta.</p><p class="muted">Secure Edge Function is the next implementation step.</p></div>`}
function view(v){if(v==="dashboard")dashboard();if(v==="vocabulary")tableView("vocabulary","Vocabulary",["word","part_of_speech","translation","level","is_active"]);if(v==="lessons")tableView("lessons","Lessons",["title","slug","level","order_index","is_published","base_xp"]);if(v==="collections")tableView("collections","Collections",["name","slug","version","is_published"]);if(v==="grammar")tableView("grammar","Grammar",["name","code","level","is_active"]);if(v==="config")config();if(v==="sync")sync()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>view(b.dataset.v));logout.onclick=async()=>{await sb.auth.signOut();boot()};boot();
